name: Node.js CI

on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ^18.1
    - run: |
        npm install
        gulp make-ts-defs
        gulp lint
        gulp bundle:cjs bundle:esm bundle:global
    - uses: actions/upload-artifact@v3
      with:
        name: lib
        path: lib

  test:

    name: test (Node.js ${{ matrix.node-version }})

    needs: build

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['14', '16', '18', '19']

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - uses: actions/download-artifact@v3
      with:
        name: lib
        path: lib
    - run: |
        npm test -- .cjs
        npm test -- .mjs
        npm test -- .min.mjs
        npm test -- .js
        npm test -- .min.js
