name: Node.js CI

on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - run: npm install
    - run: gulp make-ts-defs
    - run: gulp lint
    - run: gulp bundle:cjs bundle:esm bundle:global
    - uses: actions/upload-artifact@v2
      with:
        name: lib
        path: lib

  test:

    name: test (Node.js ${{ matrix.node-version }})

    needs: build

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - uses: actions/download-artifact@v2
      with:
        name: lib
        path: lib
    - run: npm test -- .cjs
    - run: npm test -- .mjs
    - run: npm test -- .min.mjs
    - run: npm test -- .js
    - run: npm test -- .min.js
